### ISSUE TITLE
Stuck at logging in

### ISSUE THREAD

**Issue by loonsies** [AstrubTools/dofus-protocol#1]
After changing the client version to 1.30.14, I can connect on dofus, but when I try to launch simpleBot.js to use the bot, it log in then it shows the security question then it doesn't do anything more.
```

Attempting to connect to 34.251.172.139:443 ...
Connected to 34.251.172.139:443 !
```
~~~~~~~~~~
toClient :  {"name":"HELLO_CONNECTION","params":{"key":"wodwafbcaahapzptuloriryfwjloyqdz"}}
raw toClient :  HCwodwafbcaahapzptuloriryfwjloyqdz
~~~~~~~~~~

~~~~~~~~~~
toServer :  {"name":"ACCOUNT_AUTHENTICATION","params":{}}
raw toServer :  Af
~~~~~~~~~~

~~~~~~~~~~
toClient :  {"name":"ACCOUNT_PSEUDO","params":{"nickname":"PSEUDO"}}
raw toClient :  AdPSEUDO
~~~~~~~~~~

~~~~~~~~~~
toServer :  {"name":"ACCOUNT_SERVER_LIST","params":{}}
raw toServer :  Ax
~~~~~~~~~~

~~~~~~~~~~
toClient :  {"name":"ACCOUNT_COMMUNITY","params":{"community":"2"}}
raw toClient :  Ac2
~~~~~~~~~~

~~~~~~~~~~
toClient :  {"name":"ACCOUNT_HOST","params":{"servers":[{"serverId":"601","state":1,"population":75,"requireSubscription":1},{"serverId":"605","state":1,"population":75,"requireSubscription":1},{"serverId":"609","state":1,"population":75,"requireSubscription":1},{"serverId":"604","state":1,"population":75,"requireSubscription":1},{"serverId":"608","state":1,"population":75,"requireSubscription":1},{"serverId":"603","state":1,"population":75,"requireSubscription":1},{"serverId":"607","state":1,"population":75,"requireSubscription":1},{"serverId":"611","state":1,"population":75,"requireSubscription":1},{"serverId":"602","state":1,"population":75,"requireSubscription":1},{"serverId":"606","state":1,"population":75,"requireSubscription":1},{"serverId":"610","state":1,"population":75,"requireSubscription":1}]}}
raw toClient :  AH601;1;75;1|605;1;75;1|609;1;75;1|604;1;75;1|608;1;75;1|603;1;75;1|607;1;75;1|611;1;75;1|602;1;75;1|606;1;75;1|610;1;75;1
~~~~~~~~~~

~~~~~~~~~~
toClient :  {"name":"ACCOUNT_LOGIN","params":{"time":null,"version":0}}
raw toClient :  AlK0
~~~~~~~~~~

~~~~~~~~~~
toClient :  {"name":"ACCOUNT_QUESTION","params":{"question":"Quel+est+le+lieu+de+naissance+de+ma+m%C3%A8re+%3F"}}
raw toClient :  AQQuel+est+le+lieu+de+naissance+de+ma+m%C3%A8re+%3F
~~~~~~~~~~`

**Comment by louis030195** [comment]
Good to see people have interest in this project, the code is in development and isn't "production-ready", maybe you have to tweaks some stuff, best is to compare with sniffer logs.
By the way you shouldn't debug on official server, don't get banned !
Just create an account on this [private server](https://amakna.net/) (and a character ?), the ip and port is in comment in the examples.

Anyway contributions are welcome, most of stuff to be done are:
- debugging / implementing client to server packets
- pathfinding (cells + map with a-star)

feel free to do pull requests :)

EDIT:
the problem is probably due to types in the protocol (restString, string etc. **** text protocols haha) can't really fix it right now

**Comment by loonsies** [comment]
You already done an amazing job! Well, I'm a noob in coding (it took me 1 hour to figure how to change the client version) so I was assuming it was safe since I used the random value function. Though, i'm pretty good at general tech, if you need help for anything, I'll be glad to be helpful :)

**Comment by louis030195** [comment]
I pushed an update, the login sequence works for me on amakna private server with
```bash
node examples/simpleBot.js -u [username] -p [password] -c [character] -d 0 -s 1
```
btw in examples/simpleBot.js notice the hardcoded 
```js
const dev = true // When true will try to log on amakna private server, else official
```

**Comment by loonsies** [comment]
It still get stuck at the same point, I believe there is some workaround to do to get it working with the latest update :/
